
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from openai import OpenAI
import ai_bot as ai
from pathlib import Path

from tkinter import *
# Explicit imports to satisfy Flake8



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"G:\Tkinter-Designer-1.0.7\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def _on_enter_pressed(self):
        msg = entry_1.get()
        _insert_message(msg, 'You: ')

def _insert_message(self, msg, sender):
    if not msg:
        return
    entry_1.delete(0, END)
    msg_sender = f'{sender} {msg}\n'
    self.text_widget.configure(state=NORMAL)
    self.text_widget.insert(END, msg_sender)
    self.text_widget.configure(state=DISABLED)
    self.text_widget.see(END)
    
    msg_bot = f'{ai.get_bot_name()}: {ai.get_response(msg)}\n'
    self.text_widget.configure(state=NORMAL)
    self.text_widget.insert(END, msg_bot)
    self.text_widget.configure(state=DISABLED)
    self.text_widget.see(END)

window = Tk()

window.geometry("650x450")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 450,
    width = 650,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    650.0,
    450.0,
    fill="#D9D9D9",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    280.0,
    408.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#CCC3C3",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=25.0,
    y=383.0,
    width=510.0,
    height=48.0
)
entry_1.bind('<Return>', _on_enter_pressed)
canvas.create_rectangle(
    16.0,
    80.0,
    636.0,
    370.0,
    fill="#BAA8A8",
    outline="")
# Send button
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: _on_enter_pressed,
    relief="flat"
)
button_1.place(
    x=586.0,
    y=383.0,
    width=50.0,
    height=50.0
)
# Message displayed on screen
entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    326.0,
    44.5,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=16.0,
    y=22.0,
    width=620.0,
    height=43.0
)

canvas.create_rectangle(
    69.0,
    99.0,
    539.0,
    144.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    116.0,
    183.0,
    586.0,
    228.0,
    fill="#D9D9D9",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    44.0,
    121.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    611.0,
    205.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
